import Head from 'next/head'

import Title from "../components/Design/Title";
import Logos from "../components/Design/Logos";

export default function GraphicDesign() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main className="backColor">
        <Title />       
        <Logos />
      </main>
    </div>
  )
}