import Head from 'next/head'

import Title from "../components/Home/Title";
import Services from "../components/Home/Services";
import Process from '../components/Home/Process';
import Contact from '../components/Home/Contact';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <Title />
        <Services />
        <Process />
        <Contact />
      </main>
    </div>
  )
}
